//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BslsServiceTest.BslsServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrinterInfo", Namespace="http://schemas.datacontract.org/2004/07/Jnj.ThirdDimension.BusinessLayer.BarcodeS" +
        "eries")]
    [System.SerializableAttribute()]
    public partial class PrinterInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BslsServiceTest.BslsServiceReference2.PrinterTemplate[] TemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BslsServiceTest.BslsServiceReference2.PrinterTemplate[] Templates {
            get {
                return this.TemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplatesField, value) != true)) {
                    this.TemplatesField = value;
                    this.RaisePropertyChanged("Templates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrinterTemplate", Namespace="http://schemas.datacontract.org/2004/07/Jnj.ThirdDimension.BusinessLayer.BarcodeS" +
        "eries")]
    [System.SerializableAttribute()]
    public partial class PrinterTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] VariablesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Variables {
            get {
                return this.VariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.VariablesField, value) != true)) {
                    this.VariablesField = value;
                    this.RaisePropertyChanged("Variables");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BslsServiceReference2.IBslsService", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IBslsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBslsService/OpenSession", ReplyAction="http://tempuri.org/IBslsService/OpenSessionResponse")]
        bool OpenSession(string domain, string username, string password, bool encrypted);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBslsService/OpenSessionByWWID", ReplyAction="http://tempuri.org/IBslsService/OpenSessionByWWIDResponse")]
        bool OpenSessionByWWID(decimal wwid, string password, bool encrypted);
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/IBslsService/CloseSession", ReplyAction="http://tempuri.org/IBslsService/CloseSessionResponse")]
        void CloseSession();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/GetBarcodes", ReplyAction="http://tempuri.org/IBslsService/GetBarcodesResponse")]
        string[] GetBarcodes(string seriesName, int numberOfValues);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/GetPrintersList", ReplyAction="http://tempuri.org/IBslsService/GetPrintersListResponse")]
        string[] GetPrintersList(string site);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/GetPrinterInfo", ReplyAction="http://tempuri.org/IBslsService/GetPrinterInfoResponse")]
        BslsServiceTest.BslsServiceReference2.PrinterInfo GetPrinterInfo(string printerName);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/PrintLabels", ReplyAction="http://tempuri.org/IBslsService/PrintLabelsResponse")]
        bool PrintLabels(string printerUrl, string template, string[][] data, Jnj.ThirdDimension.Service.BarcodeSeries.TemplateFieldMap[] mapping, bool stopOnError);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/GetSite", ReplyAction="http://tempuri.org/IBslsService/GetSiteResponse")]
        string GetSite(string userName, string domain);
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/GetSites", ReplyAction="http://tempuri.org/IBslsService/GetSitesResponse")]
        string[] GetSites();
        
        [System.ServiceModel.OperationContractAttribute(IsInitiating=false, Action="http://tempuri.org/IBslsService/GetSeriesNames", ReplyAction="http://tempuri.org/IBslsService/GetSeriesNamesResponse")]
        Jnj.ThirdDimension.Service.BarcodeSeries.SeriesInfo[] GetSeriesNames();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBslsServiceChannel : BslsServiceTest.BslsServiceReference2.IBslsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BslsServiceClient : System.ServiceModel.ClientBase<BslsServiceTest.BslsServiceReference2.IBslsService>, BslsServiceTest.BslsServiceReference2.IBslsService {
        
        public BslsServiceClient() {
        }
        
        public BslsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BslsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BslsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BslsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool OpenSession(string domain, string username, string password, bool encrypted) {
            return base.Channel.OpenSession(domain, username, password, encrypted);
        }
        
        public bool OpenSessionByWWID(decimal wwid, string password, bool encrypted) {
            return base.Channel.OpenSessionByWWID(wwid, password, encrypted);
        }
        
        public void CloseSession() {
            base.Channel.CloseSession();
        }
        
        public string[] GetBarcodes(string seriesName, int numberOfValues) {
            return base.Channel.GetBarcodes(seriesName, numberOfValues);
        }
        
        public string[] GetPrintersList(string site) {
            return base.Channel.GetPrintersList(site);
        }
        
        public BslsServiceTest.BslsServiceReference2.PrinterInfo GetPrinterInfo(string printerName) {
            return base.Channel.GetPrinterInfo(printerName);
        }
        
        public bool PrintLabels(string printerUrl, string template, string[][] data, Jnj.ThirdDimension.Service.BarcodeSeries.TemplateFieldMap[] mapping, bool stopOnError) {
            return base.Channel.PrintLabels(printerUrl, template, data, mapping, stopOnError);
        }
        
        public string GetSite(string userName, string domain) {
            return base.Channel.GetSite(userName, domain);
        }
        
        public string[] GetSites() {
            return base.Channel.GetSites();
        }
        
        public Jnj.ThirdDimension.Service.BarcodeSeries.SeriesInfo[] GetSeriesNames() {
            return base.Channel.GetSeriesNames();
        }
    }
}
