//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDUmbracoMembership
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwHierarchy
    {
        public int HierarchyId { get; set; }
        public Nullable<int> ParentHierarchyId { get; set; }
        public string Option { get; set; }
        public string ParentOption { get; set; }
        public int OptionId { get; set; }
        public Nullable<int> ParentOptionId { get; set; }
        public int DropDownListId { get; set; }
    }
}
