//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FowTradeDataU.umbraco.CustomWebForms {
    
    
    public partial class TDSalesForce {
        
        /// <summary>
        /// optionsGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.DynamicData.RadGridEx optionsGrid;
        
        /// <summary>
        /// hierarchyGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Telerik.Web.UI.DynamicData.RadGridEx hierarchyGrid;
    }
}
