//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jnj.ThirdDimension.Controls.BarcodeSeries.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jnj.ThirdDimension.Controls.BarcodeSeries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Query cannot be empty..
        /// </summary>
        internal static string Error_EmptyQuery {
            get {
                return ResourceManager.GetString("Error_EmptyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Name cannot be empty..
        /// </summary>
        internal static string Error_EmptySeriesName {
            get {
                return ResourceManager.GetString("Error_EmptySeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Series format should be specified..
        /// </summary>
        internal static string Error_EmptySeriesTemplate {
            get {
                return ResourceManager.GetString("Error_EmptySeriesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be less then start date..
        /// </summary>
        internal static string Error_EndDateLesser {
            get {
                return ResourceManager.GetString("Error_EndDateLesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Name already exists..
        /// </summary>
        internal static string Error_ExistedSeriesName {
            get {
                return ResourceManager.GetString("Error_ExistedSeriesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Series should have Series # or specified Year, Month and Day in digital form..
        /// </summary>
        internal static string Error_IncorrectSeriesTemplate {
            get {
                return ResourceManager.GetString("Error_IncorrectSeriesTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range is intersecting with another reservation..
        /// </summary>
        internal static string Error_IntersectingRanges {
            get {
                return ResourceManager.GetString("Error_IntersectingRanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value cannot be less then Minimum..
        /// </summary>
        internal static string Error_MaxIsLesser {
            get {
                return ResourceManager.GetString("Error_MaxIsLesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value cannot be greater than Maximum..
        /// </summary>
        internal static string Error_MinIsGreater {
            get {
                return ResourceManager.GetString("Error_MinIsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date cannot be greater then end date..
        /// </summary>
        internal static string Error_StartDateGreater {
            get {
                return ResourceManager.GetString("Error_StartDateGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required fields are filled..
        /// </summary>
        internal static string FormIsNotFilled {
            get {
                return ResourceManager.GetString("FormIsNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date is incorrect..
        /// </summary>
        internal static string Message_IncorrectDate {
            get {
                return ResourceManager.GetString("Message_IncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only change sequence and/or date.
        ///Please check if the data is correct..
        /// </summary>
        internal static string Message_IncorrectEdit {
            get {
                return ResourceManager.GetString("Message_IncorrectEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect input.
        /// </summary>
        internal static string MessageBox_IncorrectInputTitle {
            get {
                return ResourceManager.GetString("MessageBox_IncorrectInputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MessageBox_WarnTitle {
            get {
                return ResourceManager.GetString("MessageBox_WarnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS SQL Server is not supported in this version.
        ///To request the feature, contact JnJ R&amp;D, please..
        /// </summary>
        internal static string MSSQL_Unsupported {
            get {
                return ResourceManager.GetString("MSSQL_Unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to create a new sequence?
        ///Note that it will be created in {0} schema..
        /// </summary>
        internal static string Question_CreateNewSeq_Format {
            get {
                return ResourceManager.GetString("Question_CreateNewSeq_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified sequence does not exist in {0} schema.
        ///But there is a sequence with the same name in {1} schema.
        ///Do you want to use this instead?.
        /// </summary>
        internal static string Question_SeqExistsInCurrentSchema_Format {
            get {
                return ResourceManager.GetString("Question_SeqExistsInCurrentSchema_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence &apos;{0}&apos; does not exist or inaccessible and won&apos;t be updated.
        ///If you continue, next time you&apos;ll receive the same values.
        ///Proceed with printing?.
        /// </summary>
        internal static string SequenceDoesNotExist {
            get {
                return ResourceManager.GetString("SequenceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series Manager.
        /// </summary>
        internal static string TDX_Name {
            get {
                return ResourceManager.GetString("TDX_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to connect....
        /// </summary>
        internal static string Wait_Connect {
            get {
                return ResourceManager.GetString("Wait_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating sequence....
        /// </summary>
        internal static string Wait_CreatingSeq {
            get {
                return ResourceManager.GetString("Wait_CreatingSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving data from DB....
        /// </summary>
        internal static string Wait_RetrievingData {
            get {
                return ResourceManager.GetString("Wait_RetrievingData", resourceCulture);
            }
        }
    }
}
