//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpansLib.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesList
    {
        public int Id { get; set; }
        public int BatchId { get; set; }
        public string Path { get; set; }
        public string Url { get; set; }
        public System.DateTime FileDate { get; set; }
        public long FileSize { get; set; }
    
        public virtual Batch Batches { get; set; }
    }
}
