//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpansLib.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        public int Id { get; set; }
        public string JobName { get; set; }
        public string TriggerName { get; set; }
        public string Trace { get; set; }
        public System.DateTime StartDateUtc { get; set; }
        public Nullable<System.DateTime> EndDateUtc { get; set; }
    }
}
