//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpansLib.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordDefinition
    {
        public int Id { get; set; }
        public string RecordType { get; set; }
        public int FieldLength { get; set; }
        public int StartPosition { get; set; }
        public string Definition { get; set; }
        public string ValueFormat { get; set; }
        public string DateFormat { get; set; }
        public string ColumnName { get; set; }
        public string DataType { get; set; }
        public string DefaultValue { get; set; }
        public string Description { get; set; }
        public string Method { get; set; }
        public string FileFormat { get; set; }
    }
}
