//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpansLib.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTableName
    {
        public string RecordId { get; set; }
        public string FileFormat { get; set; }
        public string TableName { get; set; }
    }
}
