//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpansLib.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpanFile
    {
        public int SpanFileId { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> LoadTimeUtc { get; set; }
    }
}
