//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpansLib.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SpansEntities : DbContext
    {
        public SpansEntities()
            : base("name=SpansEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ExtraField> ExtraFields { get; set; }
        public DbSet<RecordTableName> RecordTableNames { get; set; }
        public DbSet<Batch> Batches { get; set; }
        public DbSet<FilesList> FilesLists { get; set; }
        public DbSet<RecordDefinition> RecordsDefinitions { get; set; }
        public DbSet<Relationship> Relationships { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<SpanFile> SpanFiles { get; set; }
        public DbSet<ImportLog> ImportLogs { get; set; }
        public DbSet<PaFile> PaFiles { get; set; }
    
        public virtual ObjectResult<FindMissedElements_Result> FindMissedElements()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FindMissedElements_Result>("FindMissedElements");
        }
    }
}
