//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeDataUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int HistoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Username { get; set; }
        public System.DateTime TimestampUtc { get; set; }
        public string Action { get; set; }
        public string Message { get; set; }
        public Nullable<int> ApplicationId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Application Application { get; set; }
    }
}
