//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeDataUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IPAddress()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int IPAddressId { get; set; }
        public string Ip { get; set; }
        public bool IsAdminIp { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> GeoLocationCountryId { get; set; }
        public System.DateTime LastChange { get; set; }
        public string ChangedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Site> Sites { get; set; }
    }
}
