//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradeDataUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Site()
        {
            this.IPAddresses = new HashSet<IPAddress>();
            this.Referrers = new HashSet<Referrer>();
        }
    
        public int SiteId { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public string ShadowUser { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime LastChange { get; set; }
        public string ChangedBy { get; set; }
        public int ApplicationId { get; set; }
        public bool RequireReferrerCheck { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPAddress> IPAddresses { get; set; }
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Referrer> Referrers { get; set; }
    }
}
